# Numpy

In [3]:
l1=[4,67,8,9]
l2=[1,2,3,4]
# o/p:[5,69,11,13]
out=[]
for i in l1: #4
    for j in l2: #1,2,3,4
        out.append(i+j)
out

[5, 6, 7, 8, 68, 69, 70, 71, 9, 10, 11, 12, 10, 11, 12, 13]

In [4]:
out=[]
for i in range (len(l1)):
    out.append(l1[i]+l2[i])
out    
    

[5, 69, 11, 13]

In [11]:
out=[l1[i]+l2[i] for i in range (len(l1))]
out

[5, 69, 11, 13]

In [6]:
# get the numbers which are not multiple of 3 as a list using 
# listcomprehension
mul3=[i for i in out if i%3!=0]
mul3

[5, 11, 13]

In [7]:
# replace the multiple of 3 with -1
out=[i if i%3!=0 else -1 for i in out]
out

[5, -1, 11, 13]

In [13]:
out.extend([2,8,9,6])

In [14]:
out

[5, 69, 11, 13, 2, 8, 9, 6]

In [15]:
# replace multiples of 2 with -2
# replace multiples of 3 with -1
# if it is a multiple of both replace it with -2
out1=[]
for i in out:
    if i%2==0:
        out1.append(-2)
    elif i%3==0:
        out1.append(-1)
    else:
        out1.append(i)
print(out1)
print(out)
        

[5, -1, 11, 13, -2, -2, -1, -2]
[5, 69, 11, 13, 2, 8, 9, 6]


In [16]:
out1=[]
for i in out:
    if i%2==0:
        out1.append(-2)
    elif i%3==0:
        out1.append(-1)
    else:
        out1.append(i)
print(out1)
print(out)
out2=[-2 if i%2==0 else -1 if i%3==0 else i for i in out]
print(out2)
        

[5, -1, 11, 13, -2, -2, -1, -2]
[5, 69, 11, 13, 2, 8, 9, 6]
[5, -1, 11, 13, -2, -2, -1, -2]


 # List of comphrehension nested for

In [17]:
l1,l2

([4, 67, 8, 9], [1, 2, 3, 4])

In [18]:
out=[]
for i in l1:
    for j in l2:
        out.append((i,j))
out        

[(4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (67, 1),
 (67, 2),
 (67, 3),
 (67, 4),
 (8, 1),
 (8, 2),
 (8, 3),
 (8, 4),
 (9, 1),
 (9, 2),
 (9, 3),
 (9, 4)]

In [19]:
numbers=[(i,j) for i in l1 for j in l2]
numbers

[(4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (67, 1),
 (67, 2),
 (67, 3),
 (67, 4),
 (8, 1),
 (8, 2),
 (8, 3),
 (8, 4),
 (9, 1),
 (9, 2),
 (9, 3),
 (9, 4)]

In [20]:
l2=[[23,45],[78,96],[56,12]]
# o/p:[23,45,78,96,56,12]
out2=[i for j in l2 for i in j]
out2

[23, 45, 78, 96, 56, 12]

In [21]:
# common elements in two lists using list compherension
l3=list(range(5,20,2))
l4=list(range(1,20,2))
print(l3,l4)

[5, 7, 9, 11, 13, 15, 17, 19] [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [22]:
l3=list(range(5,20,2))
l4=list(range(1,20,2))
print(l3,l4)
[i for i in l3 for j in l4 if i==j]

[5, 7, 9, 11, 13, 15, 17, 19] [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


[5, 7, 9, 11, 13, 15, 17, 19]

# Numpy
    1.numerical python
    2.vectorized programming
    3.handling multidimensional data
    4.manipulating arrays
    5.we can define the datatype
    6.commonly used with numerical data.but you may use mixed data as well
    7.faster execution
    8.less memory
    9.most of the mathematical functions are available
              -linear algebra
              -statistics
              -probability
              -fourier transform
              -trigonometric
              -logarithemic
              -exponential
      

In [23]:
# version 
import numpy
numpy.__version__ # attritube "_" -dunder

'1.16.5'

In [24]:
# importing a package with alias name
import numpy as np

# converting existing data into numpy array

In [25]:
l=[7,9,0,3,4]
np.array(l)

array([7, 9, 0, 3, 4])

In [26]:
l=[7,9,0,3,4]
array_1d=np.array(l)
print(type(array_1d))

<class 'numpy.ndarray'>


In [27]:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [28]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [29]:
t=(7,9,0,3,4)
array_1d=np.array(t)
print(type(array_1d))
print(array_1d)

<class 'numpy.ndarray'>
[7 9 0 3 4]


In [30]:
d={1:1,2:4,3:9}
np.array(d)

array({1: 1, 2: 4, 3: 9}, dtype=object)

In [31]:
d={1:1,2:4,3:9}
array_1d=np.array(list(d.values()))
array_1d

array([1, 4, 9])

In [32]:
a1=np.array(6)
print(a1)

6


In [33]:
a1=np.array(6)
print(a1)
print(type(a1))

6
<class 'numpy.ndarray'>


# Initializing arrays

In [34]:
np.zeros(3)

array([0., 0., 0.])

In [35]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
array_zeros=np.zeros((3,3))
print(array_zeros.dtype)
print(type(array_zeros))

float64
<class 'numpy.ndarray'>


In [37]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [38]:
array_zeros=np.zeros((3,3),dtype=int)
print(array_zeros.dtype)
print(type(array_zeros))


int32
<class 'numpy.ndarray'>


In [39]:
array_zeros=np.zeros((3,3),dtype=int)
print(array_zeros.dtype)
print(type(array_zeros))
print(array_zeros)


int32
<class 'numpy.ndarray'>
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [40]:
array_ones=np.ones((3,3),dtype=int)
print(array_ones.dtype)
print(type(array_ones))
print(array_ones)


int32
<class 'numpy.ndarray'>
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [41]:
array_ones=np.ones((3,3),dtype=bool)
print(array_ones.dtype)
print(type(array_ones))
print(array_ones)


bool
<class 'numpy.ndarray'>
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [42]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [43]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

# creating arrays with in specific range

In [44]:
print(np.arange(6))
print(np.arange(1,6))
print(np.arange(1,6,2))
print(np.arange(1,6,0.5))
# print(list(range(1,6,0.5)))

[0 1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]


In [45]:
print(np.linspace(1,5,10))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [46]:
print(np.linspace(1,5,10))
print(np.linspace(1,5,3))
print(np.linspace(1,5,2))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1. 3. 5.]
[1. 5.]


In [47]:
np.random.randint(10) # output range 0 to 9

3

In [48]:
np.random.randint(10,size=(2,3))

array([[1, 4, 9],
       [2, 2, 5]])

In [49]:
np.random.randint(10,size=(2))

array([8, 5])

In [50]:
np.random.randint(10,34,size=(2))

array([17, 17])

In [51]:
multi_array=np.random.randint(1,1000,size=(10,10))
multi_array

array([[ 85, 943, 119, 518, 940, 512, 536, 528, 120, 504],
       [523, 848, 998, 850, 900, 696, 193, 734, 678, 212],
       [125, 206, 992, 894, 471, 475, 889, 440, 147, 707],
       [433, 462, 699, 926, 629, 524,  89, 692, 255,  80],
       [790, 676, 759, 403, 854,  89, 833, 387, 797, 244],
       [198, 616,  84, 534, 125, 399, 468, 910, 845, 416],
       [526, 437, 690, 159, 194,  46, 776, 533, 539, 137],
       [303, 538, 616, 153, 612, 339, 996, 561, 341, 437],
       [427, 513,  25, 489,  50, 797,  35, 691, 150, 418],
       [175, 463, 152,  58, 793, 930, 925,  81, 196, 363]])

In [52]:
array_1d,array_ones,array_zeros

(array([1, 4, 9]), array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]), array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

In [53]:
print(array_1d.dtype)
print(array_1d.shape)
print(array_1d.ndim)
print(array_1d.size)
print(array_1d.dtype)
print(array_1d.dtype)

int32
(3,)
1
3
int32
int32


In [54]:
print(array_1d.dtype) # data type of the array
print(array_1d.shape) # shape as a tuple
print(array_1d.ndim)  # no of dimensions
print(array_1d.size)  # n of items in the array
print(array_1d.itemsize) # size in bytes

int32
(3,)
1
3
4


In [55]:
t=(5)
print(t,type(t))

5 <class 'int'>


In [56]:
t=(5,)
print(t,type(t))

(5,) <class 'tuple'>


# updating the values in an array

In [57]:
array_1d

array([1, 4, 9])

In [58]:
array_1d[1]=3
array_1d

array([1, 3, 9])

In [59]:
array_zeros[0]=5

array_zeros

array([[5, 5, 5],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
# how to update the 2nd row 3rd element
array_zeros[1][2]=6
array_zeros

array([[5, 5, 5],
       [0, 0, 6],
       [0, 0, 0]])

In [63]:
# chek for loop with 1d and 2d arrays
for i in array_1d:
    print(i)
    break

1


In [64]:
for i in array_zeros:
    print(i)
    break
    

[5 5 5]


# mathematical operators

In [65]:
a=np.arange(10)
b=np.arange(10,20)
print(a+b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)

[10 12 14 16 18 20 22 24 26 28]
[  0  11  24  39  56  75  96 119 144 171]
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]
[0 0 0 0 0 0 0 0 0 0]
[0 1 2 3 4 5 6 7 8 9]


In [66]:
a=np.arange(1,11)
b=np.arange(10,20)
print(a+b)
print(a*b)
print(b/a)
print(b//a)
print(b%a)
print(a**2)

[11 13 15 17 19 21 23 25 27 29]
[ 10  22  36  52  70  90 112 136 162 190]
[10.          5.5         4.          3.25        2.8         2.5
  2.28571429  2.125       2.          1.9       ]
[10  5  4  3  2  2  2  2  2  1]
[0 1 0 1 4 3 2 1 0 9]
[  1   4   9  16  25  36  49  64  81 100]


In [67]:
print(a>5)
print(a==5)
print(a<5)

[False False False False False  True  True  True  True  True]
[False False False False  True False False False False False]
[ True  True  True  True False False False False False False]
